name: Deploy React Vite Theme

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install + Build React
      - run: npm install
      - run: npm run build

      # Prepare theme folder (WordPress requires index.php + style.css)
      - name: Prepare theme package
        run: |
          mkdir luminox-react
          # copy everything from dist EXCEPT index.html
          rsync -av dist/ luminox-react/ --exclude=index.html
          # copy theme files
          cp index.php luminox-react/
          cp style.css luminox-react/
          cp .htaccess luminox-react/ || true

      # Upload theme to WordPress.com
      - name: Upload to WordPress.com
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: luminox-react
          retention-days: 1
